version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - network
  duck-service-tasks:
    build:
      context: ./Duck.Service.Tasks
      dockerfile: Dockerfile
    networks:
    - network
    depends_on:
    - mongo
volumes:
  mongo-data:
networks:
  network: